### ISSUE TITLE
Cannot run the backdate.html page

### ISSUE THREAD

**Issue by AliceNai** [kevinMEH/medium-import#11]
This is my first time using Github and I followed the steps from your article. But I cannot run the backdate.html page. ]
I received the error like The Connection has timed out. Could you please guide me?
![Screenshot 2024-05-19 at 01-52-44 Build software better together](https://github.com/kevinMEH/medium-import/assets/170092192/3f2a4e2c-f077-484b-8812-dead0bcc4a40)

**Comment by kevinMEH** [comment]
Everything looks find here, but for some strange reason it is not working for you. Try deleting your repository (go to the repository page, click the Settings tab, scroll all the way down, and delete) and then retry all the steps.

**Comment by AliceNai** [comment]
Hi Kevin,

Thank you for your reply. I tried to delete and follow your instructions
again. It worked out.
If I want to backdate multiple posts with different dates.
I need to update the timezone again and again and just keep doing the same
steps?

Many thanks,
Alice

**Comment by kevinMEH** [comment]
You shouldn't need to recreate the repository every time.

Now that you have it working, you just have to change the timestamp inside backdate.html, press the "Commit" button on the bottom to save the change, and then at the repository home page, wait for this green checkmark to show up:

<img width="332" alt="image" src="https://github.com/kevinMEH/medium-import/assets/71391217/8df5e94f-ef10-4159-8c3f-a4c329d81605">

Once the green checkmark showed up, you will know that GitHub pages is ready with the new webpage, and then you import from your GitHub pages backdate.html page. If the green checkmark does not show up, then GitHub pages may not be ready yet with the updated page, so do wait for it to show up.

Sometimes, Github pages simply fails to update, or Medium caches the backdate.html page (It remembers the old page and doesn't use the new page to import)

In that case, follow the instructions from my article, and create a new page ("backdate2.html" for example) with the contents, and then ask medium to import the new page.

**Comment by AliceNai** [comment]
Dear Kevin,

I really appreciate your instructions. I tried to set up a new page.
However, the import failed in the medium although it seems like the Github
page is showing active.
Could you please guide me on what I missed?

Thank you,
Alice

**Comment by AliceNai** [comment]
sorry, it works just now.

**Comment by kevinMEH** [comment]
👍 If you have more questions feel free to reopen this issue or create a new one.
